### PR TITLE
Usage cleanup & select statement fix

### PR DESCRIPTION
**Pull request by srtemp**
minor changes to ensure the pass only runs on selected modules, clarify usage in help statement, and handle argument parsing according to the same pattern as other yosys passes

### CODE REVIEW

**Comment by tdene** [comment]
Fair point on the alumacc pass. I missed that.

But on that topic, 2 questions:

1) Philosophically speaking, should this plugin only run alumacc specifically on the adders it will optimize itself (i.e: the ones marked with the pptrees flag)?

2) I noticed in your line of code syntax that I did not know existed. Is there some syntax that can make [these two lines](https://github.com/lnis-uofu/yosys_prefix_trees/blob/67c7f335aabba668a5086b30f43d11c9a8bcb610/src/pptrees.cc#L269) better?

**Comment by srtemp** [comment]
1) My intuition is yes; I think if the user set attributes on parts of the code, the expectation should be that it only touches those parts. Maybe add a flag to use a set of default transforms on any adders that don't have attributes set? I can see the utility of a general adder optimization pass.

2) Maybe something like:
`
RTLIL::Selection s(false);
s.select(mod, cell);
pass::call_on_selection(design, s, stringf("techmap -map %s/pptrees_alu.v %%", pptrees_dir.c_str()));
` 
Haven't tested that yet though.

**Comment by tdene** [comment]
Okay, cool! I didn't know how to do that in the Yosys code-base.

Before we merge this, I had a couple of things on my list. One was to set up an example that uses `pptrees_transforms` to show that this can generate custom adders on-the-fly. And that probably will start causing errors once it's being thoroughly tested, so will need debugging.

I don't remember what else I wanted to do, but just general improvements likely.

I think I can work on that tomorrow, and then we can merge in by Thursday. Maybe we can also borrow some cycles from @ravenslofty and have them critique the code.

**Comment by Ravenslofty** [comment]
> Maybe we can also borrow some cycles from @Ravenslofty and have him critique the code.

them.

**Review by Ravenslofty — APPROVED** [review]

**Review by tdene — APPROVED** [review]

**Pull request merged**
